LOAD DATA
 CHARACTERSET UTF8
 APPEND 
 INTO TABLE 
	FIZY_TRANSACTIONS
 FIELDS TERMINATED BY 
	"|"
 TRAILING NULLCOLS
(
	 ACCOUNT_ID       		CHAR 	
	,MSISDN					"CASE 
  								WHEN LENGTH(:MSISDN)=9 THEN 380||:MSISDN
  								ELSE :MSISDN  
  							END"
	,UNIQUE_TRANSACTION_ID	CHAR 
	,TRANSACTION_DATE		DATE 'YYYY/MM/DD HH24:MI:SS'
	,TRANSACTION_TYPE		CHAR
	,USAGE_CHANNEL			CHAR
	,MOBILE_WIFI			CHAR
	
)


