LOAD DATA
 CHARACTERSET UTF8
 APPEND 
 INTO TABLE 
	FIZY_USERS
 FIELDS TERMINATED BY 
	"|"
 TRAILING NULLCOLS
(
	 ACCOUNT_ID       	CHAR 	
	,MSISDN				"CASE 
  							WHEN LENGTH(:MSISDN)=9 THEN 380||:MSISDN
							WHEN SUBSTR(:MSISDN,1,1) = '+' THEN SUBSTR(:MSISDN,2,LENGTH(:MSISDN))
  							ELSE :MSISDN  
  						END"	
	,CREATE_DATE		DATE 'YYYY/MM/DD HH24:MI:SS'
	,GSMOPERATOR		CHAR
	,SNAPSHOT_DATE		DATE 'YYYY/MM/DD'
)


